printf "THIS SCRIPT SOLVED YOUR PROBLEM DON'T WORRY" 
sleep 2
chmod 777 ngrok
killall ngrok

printf "YOUR PROBLEM HAS BEEN SOLVED LET'S FUCK YOUR TARGET" 
sleep 2
printf "INFOSEC HACKER ACADEMY | BILAL ALI" 
